import { z } from 'zod';

import pack from '@/assets/prompts.json';

/**
 * The prompt pack: sixty curated prompts in bundled JSON.
 *
 * Not generated by a model call. Static prompts are instant, cost nothing, work
 * with no network, and are funnier — a curated list can be edited until it is
 * good, which a generated one cannot.
 */

export const TIERS = ['routine', 'contested', 'exceptional'] as const;
export type Tier = (typeof TIERS)[number];

export const PromptSchema = z.object({
  /** Stable. The daily pick and any stored history refer to prompts by id. */
  id: z.string().min(1).max(64),
  text: z.string().min(1).max(120),
  tier: z.enum(TIERS),
});

export type Prompt = z.infer<typeof PromptSchema>;

const PackSchema = z.object({
  version: z.literal(1),
  prompts: z.array(PromptSchema).min(1),
});

/**
 * The bundled pack is a build artefact, not user input — but it is still parsed
 * rather than cast. A typo in the JSON should fail loudly at startup, not
 * surface as an undefined prompt in front of a player.
 */
const PACK = PackSchema.parse(pack);

export const ALL_PROMPTS: readonly Prompt[] = PACK.prompts;

export function promptById(id: string): Prompt | null {
  return ALL_PROMPTS.find((prompt) => prompt.id === id) ?? null;
}

export function promptsInTier(tier: Tier): readonly Prompt[] {
  return ALL_PROMPTS.filter((prompt) => prompt.tier === tier);
}

/**
 * FNV-1a. Small, dependency-free, and good enough to spread dates across the
 * pack without clustering. Not a security hash and not used as one.
 */
export function hashString(value: string): number {
  let hash = 0x811c9dc5;
  for (let i = 0; i < value.length; i += 1) {
    hash ^= value.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193) >>> 0;
  }
  return hash >>> 0;
}

/** The calendar day in the device's own timezone, as YYYY-MM-DD. */
export function dayKey(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

/**
 * The daily challenge, picked from the date alone.
 *
 * Every player gets the same prompt on the same day with no server
 * coordination, no clock sync, and no request. The trade is that "the same day"
 * means the device's own calendar day, so two players in different timezones
 * change over at different moments. That is the correct trade for a game with
 * no accounts and no backend state.
 */
export function dailyPrompt(date: Date): Prompt {
  const index = hashString(dayKey(date)) % ALL_PROMPTS.length;
  // ALL_PROMPTS is non-empty by schema, so the modulo always lands in range.
  return ALL_PROMPTS[index] as Prompt;
}

/**
 * A prompt for an ordinary round. `random` takes a [0, 1) source so the caller
 * decides where randomness comes from and tests can be deterministic.
 */
export function pickPrompt(
  random: () => number,
  options: { readonly tier?: Tier; readonly excludeId?: string } = {},
): Prompt {
  const pool = options.tier === undefined ? ALL_PROMPTS : promptsInTier(options.tier);
  const candidates =
    options.excludeId === undefined
      ? pool
      : pool.filter((prompt) => prompt.id !== options.excludeId);
  // Excluding the last prompt can only empty a pool of one; fall back to it
  // rather than repeat-until-different, which could loop forever.
  const from = candidates.length > 0 ? candidates : pool;
  const index = Math.min(from.length - 1, Math.floor(random() * from.length));
  return from[index] as Prompt;
}
