import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { palette } from './tokens';

/**
 * app.config.ts holds the only two hex literals outside tokens.ts.
 *
 * They cannot be imported: Expo transpiles the config on its own and cannot
 * resolve a `.ts` import at runtime — the CLI fails with "Cannot find module
 * ./src/design/tokens". So the constraint's purpose, which is that the splash
 * cannot silently disagree with the app, is enforced here instead.
 *
 * If someone changes the palette and not the splash, this fails.
 */
const CONFIG = readFileSync(join(__dirname, '..', '..', 'app.config.ts'), 'utf8');

function hexLiterals(source: string): string[] {
  return source.match(/#[0-9a-fA-F]{6}\b/g) ?? [];
}

describe('the splash screen', () => {
  it('paints the top copy on the light scheme', () => {
    expect(CONFIG).toContain(`backgroundColor: '${palette.light.buff}'`);
  });

  it('paints the file copy on the dark scheme', () => {
    expect(CONFIG).toContain(`backgroundColor: '${palette.dark.buff}'`);
  });

  it('contains no hex literal that is not one of those two', () => {
    // A third colour appearing here is exactly the drift this file exists to
    // catch: it would be a palette value with no token behind it.
    const found = new Set(hexLiterals(CONFIG).map((hex) => hex.toUpperCase()));
    expect([...found].sort()).toEqual(
      [palette.light.buff, palette.dark.buff].map((h) => h.toUpperCase()).sort(),
    );
  });

  it('follows the system scheme rather than pinning one', () => {
    expect(CONFIG).toContain("userInterfaceStyle: 'automatic'");
  });

  it('ships an icon with no alpha, generated by the script that inspects it', () => {
    expect(CONFIG).toContain("icon: './assets/icon.png'");
  });

  it('never reads a secret from the environment or embeds key material', () => {
    // The docstring mentions the key in order to say it is not here, which is
    // correct. What must never appear is a read of it or the thing itself.
    expect(CONFIG).not.toMatch(/process\.env\.[A-Z_]*ANTHROPIC/);
    expect(CONFIG).not.toMatch(/sk-ant/);
    expect(CONFIG).not.toMatch(/process\.env\.[A-Z_]*(KEY|SECRET|TOKEN)/);
  });
});
